package com.example.ecommerce.marketplace.application.order;

import com.example.ecommerce.marketplace.domain.order.Order;
import com.example.ecommerce.marketplace.domain.order.OrderItem;
import com.example.ecommerce.marketplace.domain.order.OrderRepository;
import com.example.ecommerce.marketplace.domain.order.OrderStatus;
import com.example.ecommerce.marketplace.domain.product.ProductRepository;
import com.example.ecommerce.marketplace.domain.retailer.RetailerRepository;
import com.example.ecommerce.marketplace.domain.supplier.SupplierRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

/**
 * Use case for placing a new order in the marketplace.
 * Handles validation, order creation, and initial order setup.
 * Framework-agnostic, following Clean Architecture principles.
 */
@Service
@RequiredArgsConstructor
public class PlaceOrderUseCase {

    private final OrderRepository orderRepository;
    private final RetailerRepository retailerRepository;
    private final SupplierRepository supplierRepository;
    private final ProductRepository productRepository;

    /**
     * Executes the place order use case.
     *
     * @param command the order command containing order data
     * @return the result indicating success or failure with details
     */
    public PlaceOrderResult execute(PlaceOrderCommand command) {
        // 1. Validate required fields
        if (command.getOrderNumber() == null || command.getOrderNumber().trim().isEmpty()) {
            return PlaceOrderResult.failure("Order number is required", "INVALID_ORDER_NUMBER");
        }
        if (command.getRetailerId() == null) {
            return PlaceOrderResult.failure("Retailer ID is required", "INVALID_RETAILER_ID");
        }
        if (command.getSupplierId() == null) {
            return PlaceOrderResult.failure("Supplier ID is required", "INVALID_SUPPLIER_ID");
        }
        if (command.getShippingAddress() == null || command.getShippingAddress().trim().isEmpty()) {
            return PlaceOrderResult.failure("Shipping address is required", "INVALID_SHIPPING_ADDRESS");
        }
        if (command.getOrderItems() == null || command.getOrderItems().isEmpty()) {
            return PlaceOrderResult.failure("Order must contain at least one item", "EMPTY_ORDER_ITEMS");
        }

        // 2. Validate foreign key references exist
        // Verify retailer exists
        if (!retailerRepository.findById(command.getRetailerId()).isPresent()) {
            return PlaceOrderResult.failure("Retailer not found", "RETAILER_NOT_FOUND");
        }

        // Verify supplier exists
        if (!supplierRepository.findById(command.getSupplierId()).isPresent()) {
            return PlaceOrderResult.failure("Supplier not found", "SUPPLIER_NOT_FOUND");
        }

        // Verify all products exist
        for (PlaceOrderCommand.OrderItemCommand itemCommand : command.getOrderItems()) {
            if (itemCommand.getProductId() != null) {
                if (!productRepository.findById(itemCommand.getProductId()).isPresent()) {
                    return PlaceOrderResult.failure(
                        "Product not found with ID: " + itemCommand.getProductId(),
                        "PRODUCT_NOT_FOUND"
                    );
                }
            }
        }

        // 3. Convert command items to domain items
        List<OrderItem> orderItems = new ArrayList<>();
        for (PlaceOrderCommand.OrderItemCommand itemCommand : command.getOrderItems()) {
            if (itemCommand.getProductId() == null) {
                return PlaceOrderResult.failure("Product ID is required for all items", "INVALID_PRODUCT_ID");
            }
            if (itemCommand.getQuantity() == null || itemCommand.getQuantity() <= 0) {
                return PlaceOrderResult.failure("Quantity must be greater than 0", "INVALID_QUANTITY");
            }
            if (itemCommand.getPrice() == null || itemCommand.getPrice() < 0) {
                return PlaceOrderResult.failure("Price cannot be negative", "INVALID_PRICE");
            }

            OrderItem orderItem = new OrderItem(
                null, // ID will be generated by repository
                itemCommand.getProductId(),
                itemCommand.getQuantity(),
                itemCommand.getPrice(),
                itemCommand.getProductName()
            );

            // Validate order item using domain logic
            if (!orderItem.validate()) {
                return PlaceOrderResult.failure("Invalid order item data", "INVALID_ORDER_ITEM");
            }

            orderItems.add(orderItem);
        }

        // 4. Create order domain object
        Order order = new Order(
            null, // ID will be generated by repository
            command.getOrderNumber(),
            command.getRetailerId(),
            command.getSupplierId(),
            orderItems,
            null, // Total will be calculated
            OrderStatus.PENDING, // Initial status is PENDING
            command.getShippingAddress(),
            command.getOrderDate(),
            null // Delivery date is null initially
        );

        // 5. Validate order number format using domain logic
        if (!order.validateOrderNumber()) {
            return PlaceOrderResult.failure(
                "Invalid order number format (minimum 5 alphanumeric characters)",
                "INVALID_ORDER_NUMBER_FORMAT"
            );
        }

        // 6. Validate minimum order quantity using domain logic
        if (!order.validateMinimumOrderQuantity()) {
            return PlaceOrderResult.failure(
                "Order does not meet minimum order quantity",
                "MINIMUM_QUANTITY_NOT_MET"
            );
        }

        // 7. Calculate total amount
        Double totalAmount = order.calculateTotalAmount();
        order.setTotalAmount(totalAmount);

        // 8. Check order number uniqueness
        if (orderRepository.existsByOrderNumber(command.getOrderNumber())) {
            return PlaceOrderResult.failure("Order number already exists", "ORDER_NUMBER_EXISTS");
        }

        // 9. Save order
        Order savedOrder = orderRepository.save(order);

        // 10. Return success result with full order object
        return PlaceOrderResult.success(savedOrder);
    }
}
